PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,role TEXT NOT NULL DEFAULT 'user');
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,idea TEXT,genre TEXT,tone TEXT,language TEXT,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT);
CREATE TABLE IF NOT EXISTS scripts (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,content TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1,updated_at TEXT);
CREATE TABLE IF NOT EXISTS characters (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,name TEXT NOT NULL,role TEXT,description TEXT,traits TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS scenes (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,scene_number INTEGER NOT NULL,title TEXT,location TEXT,time_of_day TEXT,description TEXT,dialogue TEXT,visual_prompt TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS videos (id TEXT PRIMARY KEY,project_id TEXT NOT NULL,scene_id TEXT NOT NULL,prompt TEXT NOT NULL,aspect_ratio TEXT NOT NULL DEFAULT '16:9',status TEXT NOT NULL DEFAULT 'completed',model TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
