const COOKIE = 'eldab3awy_session';
const SESSION_DAYS = 30;
const enc = new TextEncoder();

async function hash(s) {
  const b = await crypto.subtle.digest('SHA-256', enc.encode(s));
  return [...new Uint8Array(b)].map(x => x.toString(16).padStart(2,'0')).join('');
}
function esc(s='') { return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
function cookie(name,val,maxAge) { return `${name}=${encodeURIComponent(val)}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`; }
function clearCookie() { return `${COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`; }
function getCookie(req,name) { const c=req.headers.get('Cookie')||''; for(const p of c.split(';')) { const [k,...v]=p.trim().split('='); if(k===name) return decodeURIComponent(v.join('=')||''); } return null; }
function page(title,body,user=null) { return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — الضبعاوي AI</title><style>
:root{--bg:#080b14;--card:#111827;--card2:#172033;--line:#26324a;--text:#f8fafc;--muted:#a8b3c7;--a:#8b5cf6;--b:#06b6d4}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#241d4a 0,#080b14 40%);color:var(--text);font-family:system-ui,-apple-system,Segoe UI,Tahoma,Arial;min-height:100vh}a{text-decoration:none;color:inherit}.nav{height:70px;border-bottom:1px solid #ffffff12;display:flex;align-items:center;justify-content:space-between;padding:0 5%;background:#080b14dd;position:sticky;top:0;z-index:4}.brand{font-size:21px;font-weight:900}.brand i{font-style:normal;color:#a78bfa}.links{display:flex;gap:14px;align-items:center}.btn{display:inline-block;padding:11px 16px;border-radius:12px;background:linear-gradient(135deg,var(--a),var(--b));font-weight:800;border:0;color:white;cursor:pointer}.wrap{width:min(1080px,92%);margin:auto;padding:42px 0}.hero{text-align:center;padding:55px 0}.hero h1{font-size:clamp(38px,7vw,72px);line-height:1.05;margin:0 0 18px}.hero h1 span{color:#a78bfa}.hero p{max-width:720px;margin:0 auto 28px;color:var(--muted);font-size:18px;line-height:1.9}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}.card{background:#111827ee;border:1px solid var(--line);border-radius:18px;padding:22px;box-shadow:0 20px 50px #0005}.form{max-width:620px;margin:15px auto}.form label{display:block;font-weight:700;margin:15px 0 7px}.input,.form textarea{width:100%;padding:13px;border:1px solid var(--line);border-radius:11px;background:#080d19;color:var(--text);font:inherit}.form textarea{min-height:340px;resize:vertical}.full{width:100%;margin-top:18px}.muted{color:var(--muted)}.err{background:#3a1118;border:1px solid #7f1d1d;padding:12px;border-radius:11px;margin:12px 0}.ok{background:#0b3026;border:1px solid #166534;padding:12px;border-radius:11px;margin:12px 0}.top{display:flex;justify-content:space-between;gap:15px;align-items:center;flex-wrap:wrap}.actions{display:flex;gap:9px;flex-wrap:wrap}.ghost{padding:10px 13px;border:1px solid var(--line);border-radius:10px}.stat{font-size:34px;font-weight:900}footer{text-align:center;color:var(--muted);padding:35px;border-top:1px solid #ffffff0d;margin-top:40px}@media(max-width:650px){.links a:first-child{display:none}.nav{padding:0 4%}}
</style></head><body><nav class="nav"><a class="brand" href="/">الضبعاوي <i>AI</i></a><div class="links">${user?'<a href="/dashboard">لوحة التحكم</a><a href="/logout">خروج</a>':'<a href="/login">دخول</a><a class="btn" href="/register">ابدأ الآن</a>'}</div></nav><main class="wrap">${body}</main><footer>© 2026 الضبعاوي AI</footer></body></html>`; }
function html(s,status=200,headers={}) { return new Response(s,{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store',...headers}}); }
function json(s,status=200) { return new Response(JSON.stringify(s),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}}); }
function red(to,headers={}) { return new Response(null,{status:302,headers:{location:to,...headers}}); }
async function user(req,env) { const t=getCookie(req,COOKIE); if(!t)return null; const row=await env.DB.prepare(`SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')`).bind(await hash(t)).first(); return row||null; }
async function session(uid,env) { const token=crypto.randomUUID()+'-'+crypto.randomUUID(); await env.DB.prepare(`INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+'||?||' days'))`).bind(crypto.randomUUID(),uid,await hash(token),SESSION_DAYS).run(); return token; }
function auth(mode,error='') { const reg=mode==='register'; return page(reg?'إنشاء حساب':'تسجيل الدخول',`<div class="card form"><h1>${reg?'إنشاء حساب جديد':'تسجيل الدخول'}</h1><p class="muted">${reg?'ابدأ حسابك على الضبعاوي AI.':'ادخل إلى مشاريعك.'}</p>${error?`<div class="err">${esc(error)}</div>`:''}<form method="post" action="/${reg?'register':'login'}">${reg?'<label>الاسم</label><input class="input" name="name" maxlength="80" required>':''}<label>البريد الإلكتروني</label><input class="input" type="email" name="email" maxlength="160" required><label>كلمة المرور</label><input class="input" type="password" name="password" minlength="8" required><button class="btn full">${reg?'إنشاء الحساب':'دخول'}</button></form></div>`); }
async function authPost(req,env,mode){ const f=await req.formData(),name=String(f.get('name')||'').trim(),email=String(f.get('email')||'').trim().toLowerCase(),pass=String(f.get('password')||''); if(!email||!pass||(mode==='register'&&!name))return html(auth(mode,'أكمل البيانات المطلوبة.'),400); if(pass.length<8)return html(auth(mode,'كلمة المرور يجب أن تكون 8 أحرف على الأقل.'),400); if(mode==='register'){if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return html(auth(mode,'البريد مسجل بالفعل.'),409);const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO users(id,name,email,password_hash) VALUES(?,?,?,?)').bind(id,name,email,await hash(pass)).run();const t=await session(id,env);return red('/dashboard',{'Set-Cookie':cookie(COOKIE,t,SESSION_DAYS*86400)});} const u=await env.DB.prepare('SELECT id,name,email,password_hash FROM users WHERE email=?').bind(email).first();if(!u||u.password_hash!==await hash(pass))return html(auth(mode,'بيانات الدخول غير صحيحة.'),401);const t=await session(u.id,env);return red('/dashboard',{'Set-Cookie':cookie(COOKIE,t,SESSION_DAYS*86400)}); }
async function dashboard(req,env){const u=await user(req,env);if(!u)return red('/login');const ps=await env.DB.prepare('SELECT id,title,description,status,updated_at FROM projects WHERE user_id=? ORDER BY updated_at DESC').bind(u.id).all();const cards=(ps.results||[]).map(p=>`<div class="card"><h3>${esc(p.title)}</h3><p class="muted">${esc(p.description||'بدون وصف')}</p><p class="muted">الحالة: ${esc(p.status)}</p><a class="ghost" href="/project/${encodeURIComponent(p.id)}">فتح المشروع</a></div>`).join('');return html(page('لوحة التحكم',`<div class="top"><div><h1>مرحبًا ${esc(u.name)} 👋</h1><p class="muted">${esc(u.email)}</p></div><a class="btn" href="/project/new">+ مشروع جديد</a></div><div class="card" style="margin:25px 0"><div class="stat">${ps.results?.length||0}</div><div class="muted">المشاريع</div></div><div class="grid">${cards||'<div class="card"><h3>لا توجد مشاريع</h3><p class="muted">أنشئ أول مشروع الآن.</p></div>'}</div>`,u));}
async function project(req,env,id,notice=''){const u=await user(req,env);if(!u)return red('/login');let p=null,s=null;if(id!=='new'){p=await env.DB.prepare('SELECT id,title,description,status FROM projects WHERE id=? AND user_id=?').bind(id,u.id).first();if(!p)return html(page('غير موجود','<div class="card"><h1>المشروع غير موجود</h1><a class="btn" href="/dashboard">رجوع</a></div>',u),404);s=await env.DB.prepare('SELECT content FROM scripts WHERE project_id=?').bind(id).first();}return html(page(p?'تحرير المشروع':'مشروع جديد',`<div class="card form" style="max-width:850px"><div class="top"><h1>${p?'تحرير المشروع':'إنشاء مشروع جديد'}</h1><a class="ghost" href="/dashboard">رجوع</a></div>${notice?'<div class="ok">تم الحفظ بنجاح.</div>':''}<form method="post" action="${p?'/project/'+encodeURIComponent(p.id):'/project/new'}"><label>اسم المشروع</label><input class="input" name="title" maxlength="200" required value="${esc(p?.title||'')}"><label>وصف المشروع</label><textarea class="input" name="description" style="min-height:120px">${esc(p?.description||'')}</textarea><label>السيناريو</label><textarea class="input" name="script" placeholder="اكتب السيناريو هنا...">${esc(s?.content||'')}</textarea><button class="btn full">💾 حفظ المشروع</button></form></div>`,u));}
async function save(req,env,id=null){const u=await user(req,env);if(!u)return red('/login');const f=await req.formData(),title=String(f.get('title')||'').trim(),description=String(f.get('description')||''),script=String(f.get('script')||'');if(!title)return project(req,env,id||'new');const pid=id||crypto.randomUUID();if(id){const ok=await env.DB.prepare('SELECT id FROM projects WHERE id=? AND user_id=?').bind(id,u.id).first();if(!ok)return html(page('غير موجود','<div class="card"><h1>المشروع غير موجود</h1></div>',u),404);await env.DB.prepare("UPDATE projects SET title=?,description=?,updated_at=datetime('now') WHERE id=? AND user_id=?").bind(title,description,id,u.id).run();}else await env.DB.prepare('INSERT INTO projects(id,user_id,title,description) VALUES(?,?,?,?)').bind(pid,u.id,title,description).run();await env.DB.prepare('INSERT INTO scripts(id,project_id,content,updated_at) VALUES(?,?,?,datetime(\'now\')) ON CONFLICT(project_id) DO UPDATE SET content=excluded.content,updated_at=datetime(\'now\')').bind(crypto.randomUUID(),pid,script).run();return id?project(req,env,id,'ok'):red('/project/'+encodeURIComponent(pid));}
export default {async fetch(req,env){try{const u=new URL(req.url),p=u.pathname.replace(/\/+$/,'')||'/';if(p==='/health'){const x=await env.DB.prepare('SELECT 1 AS ok').first();return json({ok:true,database:x?.ok===1,app:'eldab3awy-ai'});}if(p==='/'&&req.method==='GET')return html(page('الرئيسية',`<section class="hero"><h1>الضبعاوي <span>AI</span></h1><p>منصة عربية لبناء أفكار ومشاريع المحتوى بالذكاء الاصطناعي، نبدأ بأساس ثابت للمستخدمين والمشاريع والسيناريوهات.</p><div class="actions"><a class="btn" href="/register">ابدأ الآن</a><a class="ghost" href="/login">دخول</a></div></section><section class="grid"><div class="card"><h3>🎬 مشاريع</h3><p class="muted">كل فكرة في مشروع مستقل.</p></div><div class="card"><h3>📝 سيناريو</h3><p class="muted">محرر طويل مع حفظ دائم.</p></div><div class="card"><h3>🤖 AI</h3><p class="muted">جاهز لإضافة أدوات الذكاء الاصطناعي في المرحلة التالية.</p></div></section>`));if(p==='/register')return req.method==='GET'?html(auth('register')):authPost(req,env,'register');if(p==='/login')return req.method==='GET'?html(auth('login')):authPost(req,env,'login');if(p==='/logout'){const t=getCookie(req,COOKIE);if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(t)).run();return red('/',{'Set-Cookie':clearCookie()});}if(p==='/dashboard')return dashboard(req,env);if(p==='/project/new')return req.method==='GET'?project(req,env,'new'):save(req,env);const m=p.match(/^\/project\/([^/]+)$/);if(m)return req.method==='GET'?project(req,env,decodeURIComponent(m[1])):save(req,env,decodeURIComponent(m[1]));return html(page('404','<div class="card"><h1>الصفحة غير موجودة</h1><a class="btn" href="/">الرئيسية</a></div>'),404);}catch(e){console.error(e);return json({ok:false,error:'Internal Server Error'},500);}}};
